### ISSUE TITLE
Naam observedArea overal gelijktrekken binnen SensRNet

### ISSUE THREAD

**Issue by kad-floriw** [kadaster-labs/sensrnet-registry-backend#141]
Zoals beschreven in https://en.wikipedia.org/wiki/SensorThings_API#/media/File:SensorThings_API_data_model.svg

(De naam `observedArea` is op sommige plaatsen `observationArea`)

**Comment by kad-busses** [comment]
Hier was event upcasting voor nodig. Deze zijn, samen met de nieuwe event versies, geïmplementeerd in 

- https://github.com/kadaster-labs/sensrnet-registry-frontend/pull/194
- https://github.com/kadaster-labs/sensrnet-registry-backend/pull/146
- https://github.com/kadaster-labs/sensrnet-sync/pull/56
- https://github.com/kadaster-labs/sensrnet-helm-charts/pull/43
