### ISSUE TITLE
Cleanup data strategy

### ISSUE THREAD

**Issue by kad-busses** [kadaster-labs/sensrnet-registry-backend#29]
Eventstore staat niet een eenvoudige drop table / remove collection toe. Er zouden wel individuele streams verwijderd moeten kunnen worden. Kijken wat een goede strategie is om de testomgeving op te kunnen ruimen. Nu gooien we de Mongo leeg, maar de aggregates checken nog op uniekheid van email adressen.

Ideetjes:
1. eventstore streams stuk voor stuk verwijderen (soft delete vs hard delete)
2. persistent storage opnieuw aanmaken in K8s
3. ...?

Edit: misschien hoort deze issue thuis in sensrnet-ops

**Comment by kad-floriw** [comment]
Huidige opzet:
- verwijderen kan via backend als admin.
- een verwijder actie soft-delete een stream, en verwijdert het object uit mongodb
