### ISSUE TITLE
Use different NODE_ID strategy

### ISSUE THREAD

**Issue by kad-busses** [kadaster-labs/sensrnet-registry-backend#61]
Whenever we run the backend we set a NODE_ID identifier. This has impact on which and how data is shared. This NODE_ID is now set manually. This will lead (and already did during development) lead to problems when multiple nodes use the same NODE_ID. We have to come up with a different strategy. The ID has to be randomized to some extend, but also persistent for the same user.

**Comment by marcvanandel** [comment]
Randomized doesn't seem a great idea to me. It should be treated as a personal key. Actually it should be this personal that another node is not able to use the same key if it does not have some authentic part of the key...

Does multichain have a private/public key pair to be used as identification? Or should we introduce something like that?

**Comment by kad-floriw** [comment]
Goed idee! We kunnen maken dat binnen de sync-app de node-ID van binnenkomende events gezet wordt op het multichain adres van de afzender.

**Comment by marcvanandel** [comment]
NODE_ID koppelen aan Multichain 'Wallet address'
