### ISSUE TITLE
Ondersteuning voor event versies

### ISSUE THREAD

**Issue by kad-floriw** [kadaster-labs/sensrnet-registry-backend#80]
Hoe om te gaan met nieuwere versies van het datamodel?

Event Store:
	- Event upcasting
	- Alleen de central viewer leest events vanuit het netwerk, en is altijd up-to-date.

**Comment by kad-busses** [comment]
https://leanpub.com/esversioning/read

https://www.movereem.nl/files/2017SANER-eventsourcing.pdf

**Comment by marcvanandel** [comment]
**backend event versioning**
In de backend (van SensRNet) wordt event sourcing toegepast. Daar passen dan ook 'standaard' versioning strategieën bij.

**ledger event versioning**
We kunnen op dit moment niet overzien hoe de versionering van events in de ledger gaat evolueren in aankomende 10 jaar. Daarom nemen we sensitive reasoning die we vandaag wel kunnen bedenken.

We willen graag de ledger 'beschermen' tegen ongeldige events en dus ook ongeldige versies van events. Dit zou afgevangen moeten worden met smart contracts / filters.

**Comment by kad-floriw** [comment]
Closed by https://github.com/kadaster-labs/sensrnet-registry-backend/pull/79
